git:
  paging:
    colorArg: always
    pager: diff-so-fancy
    # pager: delta  --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  showDivergenceFromBaseBranch: arrowAndNumber
  allBranchesLogCmds:
    - 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline '
customCommands:
  - key: "<c-f>" # Ctrl-f (think "full screen") to show selected commit https://github.com/jesseduffield/lazygit/issues/1113
    context: "commits"
    command: "git show {{.SelectedLocalCommit.Sha}}"
    description: "Show selected commit"
    output: terminal
  - key: "<c-f>" # Ctrl-f (think "full screen") to show selected commit
    context: "files"
    command: "git diff "
    description: "Show selected commit"
    # stream: true

    output: terminal
  - key: "M" # https://github.com/jesseduffield/lazygit/issues/2461
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git mergetool"
    output: terminal
  - key: H
    command: git restore --ours {{.SelectedFile.Name | quote}}
    loadingText: "git select ours"
    context: mergeConflicts
    output: terminal
  - key: L
    command: git restore --theirs {{.SelectedFile.Name | quote}}
    loadingText: "git select theirs"
    context: mergeConflicts
    output: terminal
  - key: "W"
    command: git commit --no-verify
    context: "global"
    output: terminal
  - key: 'E'
    description: 'Add empty commit'
    context: 'commits'
    command: 'git commit --allow-empty -m "empty commit"'
    loadingText: 'Committing empty commit...'
os:
  editPreset: "nvim"
  open: "nvim {{filename}}"
gui:
  sidePanelWidth: 0.25
  statusPanelView: allBranchesLog
  showFileTree: false
  nerdFontsVersion: "3"
  mainPanelSplitMode: "horizontal"
  enlargedSideViewLocation: left
  commitHashLength: 6
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2e3c64"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
keybinding:
  commits:
    moveDownCommit: <c-x>
    moveUpCommit: <c-y>
