git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"

customCommands:
  - key: "<c-o>" # Ctrl-f (think "full screen") to show selected commit https://github.com/jesseduffield/lazygit/issues/1113
    context: "commits"
    command: "git show {{.SelectedLocalCommit.Sha}}"
    subprocess: true
    description: "Show selected commit"
    stream: true
  - key: "<c-o>" # Ctrl-f (think "full screen") to show selected commit
    context: "files"
    command: "git diff "
    subprocess: true
    description: "Show selected commit"
    # stream: true
  - key: "M"
    command: "git mergetool {{ .SelectedFile.Name }}"
    context: "files"
    loadingText: "opening git mergetool"
    subprocess: true
os:
  editPreset: "nvim"

gui:
  showFileTree: false
  nerdFontsVersion: "3"
  mainPanelSplitMode: "vertical"
  enlargedSideViewLocation: top
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2e3c64"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
