[character]
success_symbol = "[\uf054](white)" # 
vicmd_symbol = "[\ue62b](green)" # 
error_symbol = "[\uf467](red)" # 


[directory]
style = "blue bold"

[package]
disabled = true

[username]
disabled = false

[hostname]
ssh_only = true
ssh_symbol = ''
format = '[$hostname](bold dimmed green) '

[rlang]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[git_branch]
disabled = false

[git_commit]
disabled = true

[git_state]
disabled = true

[git_metrics]
disabled = false

[git_status]
disabled = true

